#!/bin/bash

# This script generates a training dataset
# containing 4k jpegs of size 256x256 pixels
# WARNING: This takes a few hours, YMMV
#          The whole sample dataset takes approx. 1.3GB of disk space.

python3 -m tensor.data --saveto data --size 4000 --dim 256
