# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api_pb2 as api__pb2


class StreamStub(object):
    """Simple streaming service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateStream = channel.unary_unary(
                '/unary.Stream/InitiateStream',
                request_serializer=api__pb2.Package.SerializeToString,
                response_deserializer=api__pb2.StreamTicket.FromString,
                )
        self.GetStream = channel.unary_unary(
                '/unary.Stream/GetStream',
                request_serializer=api__pb2.StreamTicket.SerializeToString,
                response_deserializer=api__pb2.StreamResponse.FromString,
                )


class StreamServicer(object):
    """Simple streaming service
    """

    def InitiateStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateStream': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateStream,
                    request_deserializer=api__pb2.Package.FromString,
                    response_serializer=api__pb2.StreamTicket.SerializeToString,
            ),
            'GetStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStream,
                    request_deserializer=api__pb2.StreamTicket.FromString,
                    response_serializer=api__pb2.StreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'unary.Stream', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Stream(object):
    """Simple streaming service
    """

    @staticmethod
    def InitiateStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Stream/InitiateStream',
            api__pb2.Package.SerializeToString,
            api__pb2.StreamTicket.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/unary.Stream/GetStream',
            api__pb2.StreamTicket.SerializeToString,
            api__pb2.StreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
