# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x05unary\"#\n\x07Package\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\"8\n\x0cStreamTicket\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03uri\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"^\n\x0eStreamResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x05\x12\x12\n\nnextOffset\x18\x03 \x01(\x05\x12\r\n\x05isEOF\x18\x04 \x01(\x08\x12\x0c\n\x04\x62ody\x18\x05 \x01(\x0c\x32|\n\x06Stream\x12\x37\n\x0eInitiateStream\x12\x0e.unary.Package\x1a\x13.unary.StreamTicket\"\x00\x12\x39\n\tGetStream\x12\x13.unary.StreamTicket\x1a\x15.unary.StreamResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PACKAGE']._serialized_start=20
  _globals['_PACKAGE']._serialized_end=55
  _globals['_STREAMTICKET']._serialized_start=57
  _globals['_STREAMTICKET']._serialized_end=113
  _globals['_STREAMRESPONSE']._serialized_start=115
  _globals['_STREAMRESPONSE']._serialized_end=209
  _globals['_STREAM']._serialized_start=211
  _globals['_STREAM']._serialized_end=335
# @@protoc_insertion_point(module_scope)
